// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: false,
  providers : {
    servidiesel : 'http://localhost:8000',
    transmal : 'http://localhost:8000',
  }
};
