// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: false,
  api: '',
  login_camara: 'http://177.242.104.6:8080/StandardApiAction_login.action?account=KrakenLabs&password=Kraken1234',
  camara_api : 'rtsp://v7.cmsv8.com:6604/3/3',
  apiFtlCloud : 'https://america-ftcloud.ifleetvision.com:20501',
  providers : {
    servidiesel : 'http://localhost:8000',
    transmal : 'http://localhost:8000',
  }
};
