const { writeFile, existsSync, mkdirSync } = require('fs');
const yargs = require('yargs');
const { hideBin } = require('yargs/helpers');
const dotenv = require('dotenv');

const argv = yargs(hideBin(process.argv)).argv;

const environment = argv.environment;

const isProduction = environment === 'prod';

dotenv.config({
  path: isProduction ? '.env.prod' : '.env',
});

const writeFileUsingFs = (targetPath, environmentFileContent) => {
  writeFile(targetPath, environmentFileContent, (err) => {
    if (err) console.log(err);
    if (environmentFileContent !== '') console.log(`Wrote variables to ${targetPath}`);
  });
};

const envDirectory = './projects/tracking-video/src/environments';

if (!existsSync(envDirectory)) mkdirSync(envDirectory);

const envDefaultPath = `${envDirectory}/environment.ts`;
const envDevelopmentPath = `${envDirectory}/environment.dev.ts`;

console.log(`apiServiceUrl: ${process.env.API_SERVIDIESEL_URL || ''}`);

const parseNumber = (value, fallback) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
};

const parseBoolean = (value, fallback = false) => {
  if (value === undefined) return fallback;
  return value === 'true';
};

const parseJsonObject = (value) => {
  if (!value) return {};

  try {
    const parsed = JSON.parse(value);
    return typeof parsed === 'object' && parsed !== null ? parsed : {};
  } catch (error) {
    console.warn(`Unable to parse JSON object from env value: ${value}`);
    return {};
  }
};

const formatJson = (value) => JSON.stringify(value, null, 4);

const buildEnvironmentFileContent = (
  production,
) => `// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: ${production},
  api: '${process.env.API_URL || ''}',
  login_camara: '${process.env.LOGIN_CAMARA_URL || ''}',
  camara_api : '${process.env.CAMARA_API_URL || ''}',
  apiFtlCloud : '${process.env.API_FTL_CLOUD || ''}',
  providers : {
    servidiesel : '${process.env.API_SERVIDIESEL_URL || ''}',
    transmal : '${process.env.API_TRANSMAL_URL || ''}',
  }
};
`;

writeFileUsingFs(envDefaultPath, buildEnvironmentFileContent(false));
writeFileUsingFs(envDevelopmentPath, buildEnvironmentFileContent(false));
