const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');
const dotenv = require('dotenv');

const environment = argv.environment;


const isProduction = environment === 'prod';

dotenv.config({
  path: isProduction ? '.env.prod' : '.env',
});

const writeFileUsingFs = (targetPath, environmentFileContent) => {
  writeFile(targetPath, environmentFileContent, (err) => {
    if (err) console.log(err);
    if (environmentFileContent !== '')
      console.log(`Wrote variables to ${targetPath}`);
  });
};

const envDirectory = './src/environments';

if (!existsSync(envDirectory)) mkdirSync(envDirectory);

const envDefaultPath = `${envDirectory}/environment.ts`;
const envProductionPath = `${envDirectory}/environment.prod.ts`;
const envDevelopmentPath = `${envDirectory}/environment.dev.ts`;
const firebaseMessagingSwPath = `${envDirectory}/../firebase-messaging-sw.js`;

const buildEnvironmentFileContent = (production) => `// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: ${production},
  firebase: {
    apiKey: '${process.env.FIREBASE_API_KEY || ''}',
    authDomain: '${process.env.FIREBASE_AUTH_DOMAIN || ''}',
    projectId: '${process.env.FIREBASE_PROJECT_ID || ''}',
    storageBucket: '${process.env.FIREBASE_STORAGE_BUCKET || ''}',
    messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID || ''}',
    appId: '${process.env.FIREBASE_APP_ID || ''}',
    measurementId: '${process.env.FIREBASE_MEASUREMENT_ID || ''}',
  },
  firebaseVapidKey: '${process.env.FIREBASE_VAPID_KEY || ''}',
  firebaseMessagingTokenEndpoint: '${process.env.FIREBASE_MESSAGING_TOKEN_ENDPOINT || ''}',
  api: '${process.env.API_URL || ''}',
  login_camara: '${process.env.LOGIN_CAMARA_URL || ''}',
  camara_api : '${process.env.CAMARA_API_URL || ''}',
  apiFtlCloud : '${process.env.API_FTL_CLOUD || ''}',
  tenant : '${process.env.TENANT_ID || ''}',
  sign : '${process.env.TENANT_SECRET || ''}',
  needProductos: ${process.env.NEED_PRODUCTS || false},
  enableGeoLookup : ${process.env.ENABLE_GEO_LOOKUP || true},
};
`;

const firebaseMessagingSwContent = `self.addEventListener('notificationclick', function (event) {
  const notification = event.notification;
  const target =
    notification &&
    notification.data &&
    typeof notification.data.link === 'string' &&
    notification.data.link
      ? notification.data.link
      : '/';

  notification && notification.close();

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function (clientList) {
      for (const client of clientList) {
        if ('focus' in client && client.url === target) {
          return client.focus();
        }
      }

      if (clients.openWindow) {
        return clients.openWindow(target);
      }

      return undefined;
    }),
  );
});

(function () {
  const firebaseConfig = {
    apiKey: '${process.env.FIREBASE_API_KEY || ''}',
    authDomain: '${process.env.FIREBASE_AUTH_DOMAIN || ''}',
    projectId: '${process.env.FIREBASE_PROJECT_ID || ''}',
    storageBucket: '${process.env.FIREBASE_STORAGE_BUCKET || ''}',
    messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID || ''}',
    appId: '${process.env.FIREBASE_APP_ID || ''}',
    measurementId: '${process.env.FIREBASE_MEASUREMENT_ID || ''}',
  };

  const hasRequiredConfig =
    firebaseConfig.apiKey &&
    firebaseConfig.appId &&
    firebaseConfig.messagingSenderId;

  if (!hasRequiredConfig) {
    return;
  }

  importScripts('https://www.gstatic.com/firebasejs/10.7.1/firebase-app-compat.js');
  importScripts('https://www.gstatic.com/firebasejs/10.7.1/firebase-messaging-compat.js');

  firebase.initializeApp(firebaseConfig);

  const messaging = firebase.messaging();

  messaging.onBackgroundMessage(function (payload) {
    if (payload && payload.notification) {
      return;
    }

    const title =
      (payload &&
        payload.data &&
        (payload.data.title || payload.data.notificationTitle)) ||
      'Nueva notificacion';
    const body =
      (payload &&
        payload.data &&
        (payload.data.body || payload.data.notificationBody)) ||
      'Tienes una nueva notificacion.';
    const link =
      (payload &&
        payload.fcmOptions &&
        payload.fcmOptions.link) ||
      (payload && payload.data && payload.data.link) ||
      '/';

    self.registration.showNotification(title, {
      body: body,
      icon: '/favicon.ico',
      data: {
        link: link,
      },
    });
  });
})();
`;

writeFileUsingFs(envDefaultPath, buildEnvironmentFileContent(false));
writeFileUsingFs(envDevelopmentPath, buildEnvironmentFileContent(false));
writeFileUsingFs(envProductionPath, buildEnvironmentFileContent(true));

writeFileUsingFs(firebaseMessagingSwPath, firebaseMessagingSwContent);
