// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: false,
  login_camara: 'http://177.242.104.6:8080/StandardApiAction_login.action?account=KrakenLabs&password=Kraken1234',
  camara_api : 'rtsp://v7.cmsv8.com:6604/3/3',
  api_ft_cloud : 'https://america-ftcloud.ifleetvision.com:20501',
  tenant : '3333',
  sign : '77169b8d1b1d003b438457d5782c2a4329854ed9e49036fbe85f36445cd3b3adf0f1042b9e1aed3d118b5f9e1562b641d54f18680941d69aca1d5ad41f6498568aa29d14a8d9024e20af625f69d4fa8b1bcb2f4661a858571845efadf1f5959442022c812179051bdffd11ed9506a1721513325881203471082bc7b2c4e65606aefdfd3279fc7a2fefc501f316d016c177693f2bfb9e31ca7a01fb2cb1c78a52',
  providers : {
    servidiesel : 'http://localhost:8000',
    transmal : 'http://localhost:8000',
  }
};
