// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
  production: false,
  providers : {
    servidiesel : 'http://localhost:8000',
    transmal : 'http://localhost:8000',
  },
  websocket: {
    servidiesel: {
      broadcaster: 'reverb',
      key: 'OPqUcEaBvucz3LHIIb4TQ9WDl5aTg4kA',
      host: '192.168.1.67',
      port: 8080,
      scheme: 'http',
      path: '',
      channelType: 'public',
      channel: 'tracking.{unitId}',
      event: 'vehicle.location.updated',
      namespace: false,
      enabledTransports: [
    "ws",
    "wss"
],
      authEndpoint: '/broadcasting/auth',
      authHeaders: {},
      bearerToken: '',
      withCredentials: false,
      activityTimeout: 30000,
      pongTimeout: 15000,
      unavailableTimeout: 10000,
      reconnect: {
        maxAttempts: 10,
        baseDelayMs: 1000,
        maxDelayMs: 30000,
        backoffMultiplier: 2,
      },
      throttle: {
        positionIntervalMs: 250,
        animationDurationMs: 1200,
        animationFrameMs: 16,
      },
    },
    transmal: {
      broadcaster: 'reverb',
      key: 'tracking-map-key',
      host: 'localhost',
      port: 0,
      scheme: 'http',
      path: '',
      channelType: 'public',
      channel: 'tracking.{unitId}',
      event: 'vehicle.location.updated',
      namespace: false,
      enabledTransports: [
    "ws",
    "wss"
],
      authEndpoint: '/broadcasting/auth',
      authHeaders: {},
      bearerToken: '',
      withCredentials: false,
      activityTimeout: 0,
      pongTimeout: 0,
      unavailableTimeout: 0,
      reconnect: {
        maxAttempts: 0,
        baseDelayMs: 0,
        maxDelayMs: 0,
        backoffMultiplier: 0,
      },
      throttle: {
        positionIntervalMs: 0,
        animationDurationMs: 0,
        animationFrameMs: 0,
      },
    },
  },
};
